### PR TITLE
Add eml_validate_full function

### PR DESCRIPTION
**Pull request by amoeba**
Just a programattic way to use https://knb.ecoinformatics.org/emlparser which can fully validate EML documents. `EML::eml_validate` only checks for _schema_ validity which only partly helps you know whether your document will upload successfully because Metacat Member Nodes (such as {test.}arcticdata.io) enforce additional constrains on EML documents (like custom units needing to be defined).

The response is just raw HTML but it's short and readable. Further tweaks could be made to parsing the response if desired or we could make the EML validator return a more parseable output. I decided to wait on any of that to see if this is useful in the first place.

### CODE REVIEW

**Comment by cboettig** [comment]
@amoeba We've added checks for schema-validity according to the rules in EML 2.2.1 in https://github.com/ropensci/emld/pull/27, (I believe this also includes checks for the test files included in the EML source).  If we're missing something, a bug report and/or PR against `emld`'s validation check would be super!

(Note that now the EML package simply re-exports the validation routine implemented in `emld`)

**Comment by jeanetteclark** [comment]
Nice addition @amoeba. I think it would be good for the datateam to use this as the first choice in validators for EML documents, and maybe falling back to `eml_validate` if a more familiar output along the lines of "got X element, expected Y" is needed.

Regarding the output: The HTML doesn't bother me too much, but I think it should definitely be shorter for EML documents that pass. Right now it is hard to tell at a glance whether it passed or not. This should be an easy fix though

**Comment by amoeba** [comment]
Hey @cboettig, my apologies for not pointing that out in my PR: IIRC `arcticdatautils` and the team that uses it are still on the old `EML` so they only have access to the first version of `EML::eml_validate` so this function is just a stop-gap until then.

@jeanetteclark 	That sounds like a vote for some parsing. The HTML we'd have to parse of clean up is generated in https://github.com/NCEAS/eml/blob/4417cbf6588fdca4e06bd67190a9d7a18a8e944f/src/main/java/org/ecoinformatics/eml/EMLParserServlet.java#L239-L302.

**Comment by amoeba** [comment]
The #135 PR just landed and we're working through it now. It obviates any need for this PR. I'll leave this open but feel free to close when we merge the EML2 refactor.

**Comment by amoeba** [comment]
Now that the eml2 branch is merged, do we still want this for any reason? I'm in favor of deleting this PR so we get everyone using `eml_validate`. Any differences between the Metacat EMLValidator and `EML::eml_validate` should get resolved and having a path around improving `EML::eml_validate` won't help.

**Comment by dmullen17** [comment]
That's ok with me

**Comment by amoeba** [comment]
Closing as discussed. If anyone still wants this, feel free to comment or reopen.

**Pull request closed without merging**
