### PR TITLE
Update eml@packageId element in update_object

### LINKED ISSUE #53: update_object doesn't update identifier field for EMLs
Using `update_object` to update a metadata record doesn't set the packageId (eml@packageId) as the pid of the most recent version.  
I'd be happy to update this (if it's a worthy change) - filing it as an issue so I don't forget.

### PR DESCRIPTION
**Pull request by dmullen17**
Resolve #53   Modified `update_object` to set the `eml@packageId` element to the newly generated pid if the `format_id` is a variant of eml://ecoinformatics.org/eml-...

### CODE REVIEW

**Comment by amoeba** [comment]
Awesome, thanks! Looks good to me. Have you tested this yourself?

**Comment by dmullen17** [comment]
Can't believe I forgot to test it >.<.  It works now that it re-calculates the checksum after updating `eml@packageId`.  

Here's the test: 
```cn <- CNode('STAGING')
mn <- getMNode(cn,'urn:node:mnTestARCTIC')
source("/home/dmullen/R/update_object_test.R")
test_pid <- publish_object(mn, path = "/home/dmullen/Choi/science_metadata.xml",
                           format = format_eml())
update_object_test(mn, test_pid,
                   path = "/home/dmullen/Choi/science_metadata.xml",
                   format = format_eml())```

**Comment by amoeba** [comment]
Excellent, thanks @dmullen17 🎉  ! It's awesome to have help fixing bugs like these!

**Comment by dmullen17** [comment]
Happy to help!

**Pull request merged**
