### PR TITLE
added userId to the eml_party functions

### PR DESCRIPTION
**Pull request by jeanetteclark**
I think I got it right...lots of things unrelated to my function seemed to fail when I ran testthat though. Still not so sure on that part of things

### CODE REVIEW

**Comment by amoeba** [comment]
PS this otherwise looks great and thanks for putting this together! I haven't finished my coffee yet and I hope my manners are at the bottom of this first cup.

**Comment by jeanetteclark** [comment]
this is what I get for trying to do this at 4:45 on a Friday - didn't realize that directory was required until now. 

what directories are we likely to see? ORCID and maybe LDAP? seems like it would be fairly easy to try and guess those two and return an error or warning otherwise

**Comment by amoeba** [comment]
basically all ORCIDs, so you could look for orcid.org as a substring of the provided value and autofill https://orcid.org. You *could* also validate what they put in by validating on a substring. Say, they get a warning if what they provide doesn't start with `https://orcid.org/`.

**Comment by jeanetteclark** [comment]
if we are anticipating all orcids, then we should just set the directory to `https://orcid.org` as the default. Would the userId then be `https://orcid.org/0000-0003-4703-1974` or just the numbers?

**Comment by amoeba** [comment]
I forget what we had decided. I can take a look at the ORCID guidelines which should help steer us in the right direction. Typically ORCIDs shouldn't be divorced from their `https://orcid.org/` prefix

**Comment by jeanetteclark** [comment]
that is what I was thinking too. So we can set the directory automatically (maybe with a warning?) and throw an error if the actual UserId doesn't have the prefix in there correctly

**Comment by amoeba** [comment]
Sounds great to me!

**Comment by mbjones** [comment]
We concluded that the identifier used should include the https URI, even though it is redundant with the directory attribute.  So, all userId values for ORCIDs should be in the format:

https://orcid.org/WWWW-XXXX-YYYY-ZZZZ

**Comment by jeanetteclark** [comment]
I added the directory and a placeholder for the warning, I'm not sure how to write warnings/errors

**Comment by amoeba** [comment]
Looks great, @jeanetteclark. Thanks for taking care of this! I'll add you as a contributor to the package.

**Pull request merged**
